
services:
  xtrafik-app:
    build:
      context: ./backend
      args:
        BUILDTIME: "${BUILDTIME:-dev}"
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app/frontend
